tap "homebrew/cask"

brew "carthage"
brew "cocoapods"
brew "ffmpeg"
brew "git-flow"
brew "imagemagick"
brew "jq"
brew "rbenv"
brew "ruby-build"

cask "charles"
cask "dropbox"
cask "insomnia"
cask "jasper"
cask "kindle"
cask "figma"
cask "fork"
cask "responsively"
cask "sequel-ace"
cask "slack"
cask "visual-studio-code"
cask "zettlr"
cask "zoom"